# Generated by Django 4.0.1 on 2022-01-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
