# Generated by Django 4.0.1 on 2022-01-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0005_alter_post_options_post_created_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogImage',
            field=models.ImageField(blank=True, null=True, upload_to='Featured-image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.SET_NULL, to='theBlog.categories'),
        ),
    ]
