# Generated by Django 4.0.1 on 2022-01-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0009_delete_tag_room_tag_alter_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
        migrations.AddField(
            model_name='room',
            name='tag',
            field=models.ManyToManyField(to='theBlog.Categories'),
        ),
    ]
