# Generated by Django 4.0.1 on 2022-01-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0010_remove_room_tag_room_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
