# Generated by Django 4.0.1 on 2022-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0014_remove_room_topic_topic_topic_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_room',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ManyToManyField(related_name='room_topic', to='theBlog.Topic'),
        ),
    ]
