# Generated by Django 4.0.1 on 2022-02-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theBlog', '0018_alter_message_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.AddField(
            model_name='topic',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theBlog.room'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
