# Generated by Django 4.0.1 on 2022-02-25 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theBlog', '0019_rename_message_comment_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='participates',
            field=models.ManyToManyField(related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
