# Generated by Django 4.0.1 on 2022-02-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0020_topic_participates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
